### PR TITLE
Emit interlacing flag.

### PR DESCRIPTION
**Pull request by ben0x539**

### CODE REVIEW

**Comment by nwin** [comment]
Thank you, but that alone doesn’t make much sense unless the image itself encoded interlaced. One would need to reorder the rows as well.

**Comment by nwin** [comment]
Admittedly the API is not optimal. It needs to be clarified what `Frame` contains. Probably it would be best to introduce a low- and high-level API. Where `RawFrame` contains the raw image data and `Frame` processed image data (like de-interlaced RGBA data).

**Comment by ben0x539** [comment]
My use case was reading a gif, mixing up the frames a little while leaving the actual image data untouched, and then writing the frames out again. Without this change, the frames would stay encoded the same way but lose the interlaced flag and so it wouldn't roundtrip interlaced frames.

**Comment by nwin** [comment]
Good point.

**Pull request merged**
