### PR TITLE
Implement deinterlacing

### LINKED ISSUE #25: decode interlaced gifs
The decoder stores an interlaced flag in the Frame, but currently nothing makes use of this.

Any preference on the design for implementing this?  I think we will need to call fill_buffer() repeatedly for each scanline.  This will require a new function that always reads an entire frame, since I can't see how to sanely handle partial reads of multiple scanlines otherwise.

Also, I noticed that the gif read_scanline() implementation in piston-image is returning the row length. It should be returning the row index I think? So we'll probably need a new function in image-gif that reads a single scanline too, and returns the row index.

### PR DESCRIPTION
**Pull request by philipc**
Closes #25 

The image crate will need to change from fill_buffer() to read_buffer() to benefit from this.

Note that I also changed read_next_frame() to clear the interlaced flag in case callers were using that to implement deinterlacing themselves.

### CODE REVIEW

**Comment by nwin** [comment]
Thank you for your contribution.

The reason I didn't implement any interlace yet was that I was unsure how to best handle it. I think your handling goes in the right direction.

`read_next_frame` is a convenience function thus I think it'll be fine to lie about the interlaced flag.

`read_buffer` might be used in more performance critical code thus I think it shouldn't return an `Vec<u8>` but take an `&mut [u8]` such that the memory could be re-used. Probably it should be rename to `read_into_buffer` to adhere to Rusts naming conventions.

I have more of a problem with the scanline flag. It's purely an implementation detail of the de-interlacer an thus shouldn't be part of the `Frame` as the frame only contains information that are present in the image as well. I would either convert `next_row` into an iterator or just let it take height and scanline on every call. In both cases it could be moved out of the `impl`. The iterator approach is cleaner but more tedious as Rust doesn't support generators yet.

**Comment by philipc** [comment]
Note that the scanline flag is in `Reader`, not `Frame`. I'll still see what I can do to remove it though.

**Comment by philipc** [comment]
I've updated the request with my attempt to use an iterator. I'm not sure this is better than a function though. I also changed `read_buffer` to `read_into_buffer`.

**Comment by nwin** [comment]
Wow...that was fast. Thanks a lot, looks good so far. I'll have a closer look when I'm not on mobile any more.

**Comment by philipc** [comment]
I did some more changes to this... I saw in some other issues that `read_scanline` needs to be deprecated, so that removed my motivation to expose the iterator. That let me simply some things. We can make the iterator public later if needed, but I prefer this simpler fix for now. I also fixed a corner case in the iterator (height < 4).

**Comment by nwin** [comment]
Great! Thank you for contributing!

**Comment by philipc** [comment]
Thanks for the review. What needs to be done to make this usable in the image crate?

**Pull request merged**
