### PR TITLE
fix gif encoding for frames with only 2 colors

### PR DESCRIPTION
**Pull request by billiob**
I generated some frames with only 2 colors and `gifsicle` complained about the file being corrupted.
According to https://www.w3.org/Graphics/GIF/spec-gif89a.txt, paragraph
ESTABLISH CODE SIZE on page 31:
> images which have one color bit must be indicated as having a code size of 2.
I've added a test with such a file.

### CODE REVIEW

**Comment by nwin** [comment]
Thanks, for catching this. I'll look into it. Would you consent to releasing you r changes under dual-license MIT/Apache 2?

Great. I love specs that are lying and imprecise at the same time. Monochrome images are apparently allowed to have a code size of 1.  😕

**Comment by billiob** [comment]
I accept to release my changes dual-license MIT/Apache 2.

**Comment by billiob** [comment]
I couldn't find information saying that a `min_code_size` of 1 is allowed for monochrome images.
How do you want to process?

**Comment by nwin** [comment]
Merge it as soon as if I had time to review it. Sorry for the delay.

**Comment by nwin** [comment]
Thank you for your contribution. I’m closing in favor of #21 as I preferred a slightly different test setup.

**Pull request closed without merging**
